name: Testes e Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-and-build:
    name: Testes e Build
    runs-on: ubuntu-latest

    services:
      # Serviço Redis para testes de integração
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Verificar versão do Go
        run: go version

      - name: Download das dependências
        run: |
          go mod download
          go mod verify

      - name: Executar testes unitários
        run: go test -v -race -cover ./...
        env:
          REDIS_ADDR: localhost:6379

      - name: Verificar cobertura de testes
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out

      - name: Build do projeto
        run: |
          GOOS=linux GOARCH=amd64 go build -v -o bin/app-linux
          GOOS=windows GOARCH=amd64 go build -v -o bin/app.exe

      - name: Arquivar binários
        uses: actions/upload-artifact@v3
        with:
          name: binarios
          path: bin/
          retention-days: 5
