# Workflow for building and testing a Go project
# Documentation: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Build and Test Go Project
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      go_version: '1.20' # Update this value to change the Go version globally

    steps:
      # Step: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step: Set up the Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go_version }}

      # Step: Build the project
      - name: Build
        run: go build -v ./...

      # Step: Run tests
      - name: Test
        run: go test -v ./...